### ISSUE TITLE
Do you plan to submit this plugin to logstash-plugin org ?

### ISSUE THREAD

**Issue by wiibaa** [dstore-dbap/logstash-output-webhdfs#3]
Hello, question is in the title :)
More info: http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html#_contributing_your_source_code_to_ulink_url_https_github_com_logstash_plugins_logstash_plugins_ulink_3

**Comment by dstore-dbap** [comment]
Well, I already send a pull request to them a couple of month ago but it seemed they were not merging in any pulls. Maybe because they were in the transition from logstash-contrib to logstash-plugins. Though you are right, could try it again. Will have to take a look at their current requirements first.

**Comment by loshkovskyi** [comment]
Yes, there is a requirement in Logstash 1.5 for all of the plugins to be separate Ruby gems.

**Comment by dstore-dbap** [comment]
Changed the plugin structure to reflect the pattern described in http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html#_contributing_your_source_code_to_ulink_url_https_github_com_logstash_plugins_logstash_plugins_ulink_3.

Added plugin to rubygems.org, so it can now be installed via:
```
bin/plugin install logstash-output-webhdfs
```

**Comment by dstore-dbap** [comment]
@wiibaa Closing this now since we got it merged now. See https://github.com/logstash-plugins/logstash-output-webhdfs.
